name: CD - Promoción y Despliegue de Modelo

on:
  workflow_dispatch:

jobs:
  deploy-model:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Descargar artefactos del run anterior
        uses: actions/download-artifact@v4
        with:
          name: mlruns
          path: mlruns/

      - name: (Opcional) Mostrar ruta del modelo descargado
        run: |
          echo "Buscando carpeta del modelo en mlruns..."
          find mlruns -path "*/artifacts/model/MLmodel" -print || true

      - name: Promocionar modelo (simulado)
        run: |
          echo "✅ Promoción del modelo validado a producción"
          # Aquí podrías:
          # - Registrar en MLflow Model Registry (mlflow.register_model)
          # - Cambiar stage a 'Production'
          # - O preparar un paquete para servir (mlflow models build/serve)